name: "Beta: Feedback"
description: "General feedback for the beta."
labels: ["feedback"]
body:
  - type: textarea
    id: text
    attributes:
      label: Feedback
      value:
    validations:
      required: true
