name: Frontend
on:
  pull_request:
  push:
    paths:
      - frontend/**

jobs:
  frontend:
    name: Lint and Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
      - name: Install dependencies
        run:
          npm ci
      - name: index.css
        run:
          cat src/index.css
      - name: Run ESLint
        run:
          npm run eslint
      - name: Run Prettier Check
        run:
          npm run prettier:check
      - name: Run Tests
        run:
          npm run test
