on:
  pull_request:
  push:
    paths:
      - '*.tsx?'

jobs:
  frontend:
    name: Linting
    working-directory: frontend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
      - name: Install dependencies
        run:
          npm ci
      - name: Run linting
        run:
          npm run lint
